create table users(
                      user_id int generated by default as identity primary key,
                      username varchar(20),
                      userPassword varchar(15)
);

create table coolerTable(
                            id int generated by default as identity primary key,
                            manufacturer varchar(20),
                            model varchar(50),
                            TDP int
);

create table cpuTable(
                         id int generated by default as identity primary key,
                         manufacturer varchar(20),
                         model varchar(50),
                         socket varchar(10),
                         cores int,
                         threads int,
                         frequency float,
                         memoryType varchar(10),
                         TDP int
);

create table gpuTable(
                         id int generated by default as identity primary key,
                         manufacturer varchar(20),
                         model varchar(50),
                         memory int,
                         MHzFrequency float,
                         memoryType varchar(10),
                         rayTracing varchar(3),
                         requiredPowerSupply int
);


create table hddTable(
                         id int generated by default as identity primary key,
                         manufacturer varchar(20),
                         model varchar(50),
                         memory int
);

create table motherboardTable(
                                 id int generated by default as identity primary key,
                                 manufacturer varchar(20),
                                 model varchar(50),
                                 formFactor varchar(10),
                                 socket varchar(10),
                                 countOfRamPlanks int,
                                 memoryType varchar(10),
                                 m2Count int,
                                 sataCount int
);

create table powerSupplyTable(
                                 id int generated by default as identity primary key,
                                 manufacturer varchar(20),
                                 model varchar(50),
                                 power int,
                                 sataCount int
);

create table ramTable(
                         id int generated by default as identity primary key,
                         manufacturer varchar(20),
                         model varchar(50),
                         type varchar(10),
                         memory int,
                         MHzFrequency int
);

create table ssdTable(
                         id int generated by default as identity primary key,
                         manufacturer varchar(20),
                         model varchar(50),
                         memory int
);

create table ssdM2Table(
                           id int generated by default as identity primary key,
                           manufacturer varchar(20),
                           model varchar(50),
                           memory int
);

create table configuration(
                              user_id int,
                              cooler_id int,
                              cpu_id int,
                              gpu_id int,
                              hdd_id int,
                              motherboard_id int,
                              powerSupply_id int,
                              ram_id int,
                              ssd_id int,
                              ssdM2_id int
);
